Add *_RTE, *_ANY_RTE and *_NO_RTE assertions
byte-physics/igortest pull request #418
Opened 2023-02-24 13:59 UTC by Garados007

These assertions check the current RTE state and create an error if its
unexpected. This simplifies the user code to check for RTEs during
runtime.

Close #339

2023-02-24 14:10 UTC, Garados007 commented
@t-b @MichaelHuth Ready for review.

2023-02-24 18:30 UTC, t-b commented
Very nice addition!

The assertions work as expected. I do have some questions about the example though ;)

- TestWaveOp: Whitespace in separate commit would be nice. But why remove `AbortOnRTE`? And if that is the right thing to do the print message should not mention it anymore.
- TestWaveOpSafe: This seems to be a better way to do things. Can we maybe rename that test case? And I'm wondering why we still need to have the try/catch? With the new assertions I would just do

```igorpro
	INFO("checks if CustomUserFunction returns with no RTE")
	CustomUserFunction()
	CHECK_NO_RTE()
```
or?

2023-02-24 18:31 UTC, t-b requested changes
See comment

2023-02-25 10:02 UTC, Garados007 commented
> Whitespace in separate commit would be nice. 

👍 

> But why remove AbortOnRTE?

I forgot to put it back after experimenting.

> And I'm wondering why we still need to have the try/catch?

At this part I want to show that the user can now handle RTE and aborts differently. Previously, the user has to add `AbortOnRTE` and handle both in the `catch`-block.

2023-02-25 13:36 UTC, Garados007 commented
Fixed it.

2023-02-27 13:33 UTC, t-b approved these changes

2023-02-27 13:33 UTC, merged