Add SKIP_TESTCASE and SKIP_TESTCASE_EXPECT_FAILS assertions
byte-physics/igortest pull request #470
Opened 2024-06-06 16:00 UTC by MichaelHuth

Both assertion abort the current testcase. Any registered reentry function is unregistered.

When SKIP_TESTCASE_EXPECT_FAILS is called, previously failed assertions in the same testcase are treated as expected failures.

close #467

2024-06-24 11:36 UTC, Garados007 requested changes
I am missing some test cases that call these new assertions and check if

1. the output in the log is as expected (you are changing the order of the info output calls, so I would expect a test for this).
2. the test results are correctly stored in the global waves. Doing this ensures that igortest handles the new assertions correctly and the output (e.g. junit) is as expected.

2024-07-16 16:58 UTC, MichaelHuth commented
I did not change the order of the output, the output is just moved to an own function.

I added some tests that check if the TCs are correctly counted as skipped.

2024-07-17 13:00 UTC, Garados007 commented
I am just curious. Wouldn't `tests/TestResultsTests/EasyTests.ipf` be a more fitting place for the tests than `tests/Various.ipf`?

2024-07-19 11:21 UTC, MichaelHuth commented
Ok I moved it.

2024-07-19 12:15 UTC, Garados007 approved these changes

2024-07-19 12:17 UTC, Garados007 commented
LGTM

@t-b It seems like you have to approve this PR as code owner

2024-07-19 12:57 UTC, merged